// Copyright 2026 The Eigenius Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! **D67 §6 (3.5) acceptance** — the demo's core, in-process: both paragraph variants'
//! generated claim layers land on branches of the snapshot working copy, the hand-authored
//! vocabulary + rule + inference load on top, and the D39 gate says **Holds** for the intact
//! inference and **Fails** for the edited one (its antecedent's witness never existed — the
//! negated measurement parses to `⟨term⟩ → False`, a different proposition, a different witness
//! key). In-process caveat (ingest.rs): the gate verdict is computed post-hoc here; the served
//! path (`demo/prose-to-formulas/run.sh`) rejects at commit through the AutoOnLoad gate.
//!
//!   EIGENIUS_DB_SNAPSHOT=/path/to/wordnet-umls-aligned-2026-08-12-d67 \
//!     cargo test --release -p eigenius-encoding --test acceptance -- --ignored --nocapture
//!
//! The artifacts are the COMMITTED ones (`demo/prose-to-formulas/claims-*.esl`), regenerated by
//! `prose-to-esl` on the same snapshot family — this test consumes, it does not parse.

use std::path::PathBuf;
use std::sync::Arc;

use eigenius_encoding::snapshot::open_head_and_backend;
use eigenius_kernel::commit::{BackendPersister, LayerPersister};
use eigenius_kernel::context::{ExecutionContext, ExecutionMode};
use eigenius_kernel::esl;
use eigenius_kernel::layer::{Layer, LayerBuilder, LayerStorage};
use eigenius_kernel::ontology::resource::{Resource, Value};
use eigenius_kernel::ontology::Iri;
use eigenius_kernel::storage::PersistentBackend;
use eigenius_reasoning::validate::do_validate_justification;
use eigenius_reasoning::ReasoningInstitution;

fn repo(rel: &str) -> String {
    format!("{}/../../{rel}", env!("CARGO_MANIFEST_DIR"))
}

/// Compile `src` against `head`, build ON the persistent store (§7-2: an in-memory layer over
/// the DB base OOMs at index build), and advance `branch` to it.
fn load_layer(
    backend: &Arc<dyn PersistentBackend>,
    head: &Arc<Layer>,
    branch: &str,
    name: &str,
    src: &str,
) -> Arc<Layer> {
    let resources = esl::compile_against_layer(src, head)
        .unwrap_or_else(|e| panic!("{name} compiles against the chain: {e:?}"));
    let mut b = LayerBuilder::new(name, Some(Arc::clone(head)));
    for r in resources {
        b.add_resource(r)
            .unwrap_or_else(|e| panic!("{name}: {e:?}"));
    }
    let layer = Arc::new(b.build(LayerStorage::with_persistent(Arc::clone(backend))));
    let persister = BackendPersister::new(Some(Arc::clone(backend)));
    let info = persister.persist(branch, &layer).expect("persist");
    assert!(info.branch_advanced, "{name} advances {branch}");
    layer
}

/// The D39 gate verdict on `sentence_iri`, validated against the chain at `head`.
fn gate_verdict(head: &Arc<Layer>, sentence: &Resource) -> (String, Option<String>) {
    let ctx = ExecutionContext::new(
        Arc::clone(head),
        "acceptance",
        ExecutionMode::ReadOnly,
        LayerStorage::in_memory(),
    );
    let institution = ReasoningInstitution::new();
    match do_validate_justification(&institution, sentence, &ctx) {
        Ok(outcome) => {
            let ctor = outcome
                .output
                .get(&Iri::parse(eigenius_kernel::ontology::well_known::CTOR_NAME).unwrap())
                .and_then(Value::as_str)
                .unwrap_or_default()
                .to_string();
            let diag = outcome
                .output
                .get(&Iri::parse("urn:eigenius:institution:diagnostic").unwrap())
                .and_then(Value::as_str)
                .map(str::to_owned);
            (ctor, diag)
        }
        Err(e) => ("Err".to_string(), Some(format!("{e:?}"))),
    }
}

#[test]
#[ignore = "DB-backed 3.5 acceptance; set EIGENIUS_DB_SNAPSHOT + run --ignored --nocapture"]
fn intact_inference_holds_and_edited_is_refused() {
    let Some(snap) = std::env::var("EIGENIUS_DB_SNAPSHOT")
        .ok()
        .map(PathBuf::from)
    else {
        eprintln!("SKIP: EIGENIUS_DB_SNAPSHOT unset");
        return;
    };
    let (base, backend) = match open_head_and_backend(&snap) {
        Ok(x) => x,
        Err(e) => {
            eprintln!("SKIP: {e}");
            return;
        }
    };
    let read = |rel: &str| std::fs::read_to_string(repo(rel)).expect("demo file reads");

    // 1. Vocabulary + the pinned literature rule, shared by both branches (run.sh step 1).
    let head = load_layer(
        &backend,
        &base,
        "main",
        "encoding",
        &read("ontologies/encoding/encoding.esl"),
    );
    let head = load_layer(
        &backend,
        &head,
        "main",
        "onco-typed",
        &read("demo/prose-to-formulas/onco-typed.esl"),
    );
    let head = load_layer(
        &backend,
        &head,
        "main",
        "literature-rules",
        &read("demo/prose-to-formulas/literature-rules.esl"),
    );

    // 2. INTACT: claims + the inference — the gate must say Holds (justified by derivation,
    //    independently of sentence 2 asserting the same proposition).
    backend
        .put_branch("demo-intact", head.id())
        .expect("point demo-intact at the shared head");
    let intact_claims = load_layer(
        &backend,
        &head,
        "demo-intact",
        "claims-intact",
        &read("demo/prose-to-formulas/claims-intact.esl"),
    );
    let intact = load_layer(
        &backend,
        &intact_claims,
        "demo-intact",
        "inference-intact",
        &read("demo/prose-to-formulas/inference.esl"),
    );
    let sentence = intact
        .resolve(&Iri::parse("urn:eigenius:demo:formulas:inferred:sentence").unwrap())
        .expect("the inferred sentence is on the branch");
    let (ctor, diag) = gate_verdict(&intact, &sentence);
    eprintln!("intact verdict: {ctor} {diag:?}");
    assert_eq!(
        ctor, "Holds",
        "the INTACT inference must Hold — RequiresActivity is justified by derivation: {diag:?}"
    );

    // 3. EDITED: the negated measurement — same inference file, no witness for its antecedent.
    backend
        .put_branch("demo-edited", head.id())
        .expect("point demo-edited at the shared head");
    let edited_claims = load_layer(
        &backend,
        &head,
        "demo-edited",
        "claims-edited",
        &read("demo/prose-to-formulas/claims-edited.esl"),
    );
    let edited = load_layer(
        &backend,
        &edited_claims,
        "demo-edited",
        "inference-edited",
        &read("demo/prose-to-formulas/inference.esl"),
    );
    let sentence = edited
        .resolve(&Iri::parse("urn:eigenius:demo:formulas:inferred:sentence").unwrap())
        .expect("the inferred sentence resource still builds");
    let (ctor, diag) = gate_verdict(&edited, &sentence);
    eprintln!("edited verdict: {ctor} {diag:?}");
    assert_ne!(
        ctor, "Holds",
        "the EDITED inference must NOT hold — its antecedent's witness never existed"
    );
    let diag = diag.unwrap_or_default();
    eprintln!("edited diagnostic (surfaced): {diag}");
    assert!(
        !diag.is_empty(),
        "the refusal carries a diagnostic — the run.sh:222 gap, surfaced here"
    );
}
