// Copyright 2026 The Eigenius Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! **The residue-versus-variant toy** (UAB Round 1, experiment 01), in-process over the lexicon
//! snapshot: the survey sentence lands as a parsed claim, a declared bridge lifts its report to
//! the variant-level `DDAVPResponsive`, and the kernel's commit-time certificate check decides four
//! conclusions (`experiments/residue-variant/`):
//!
//! | case | conclusion | expected |
//! |---|---|---|
//! | A | `DDAVPResponsive(Leu44)` | refused — `Leu44` is a `Residue` |
//! | B | `DDAVPResponsive(c.131T>C)` | refused — the survey says nothing about c.131T>C |
//! | C | `SurveyReportsResponsive(Leu44)` | commits — the sentence, cited for what it says |
//! | D | `DDAVPResponsive(c.131T>C)` with the declared inverse of `HasResidue` | commits |
//!
//!   EIGENIUS_DB_SNAPSHOT=../db-snapshot/uab-compound-aligned-2026-10-01 \
//!     cargo test --release -p eigenius-encoding --test residue_variant -- --ignored --nocapture
//!
//! `claims.esl` is the COMMITTED artifact, regenerated by `prose-to-esl` (replaying
//! `selections.json`) on the same snapshot family — this test consumes, it does not parse.

use std::path::PathBuf;
use std::sync::Arc;

use eigenius_encoding::snapshot::open_head_and_backend;
use eigenius_kernel::commit::{BackendPersister, LayerPersister};
use eigenius_kernel::esl;
use eigenius_kernel::layer::{Layer, LayerBuilder, LayerStorage};
use eigenius_kernel::storage::PersistentBackend;

fn repo(rel: &str) -> String {
    format!("{}/../../{rel}", env!("CARGO_MANIFEST_DIR"))
}

/// Compile `src` against `head`, build ON the persistent store (an in-memory layer over the DB base
/// OOMs at index build), and advance `branch` to it.
fn load_layer(
    backend: &Arc<dyn PersistentBackend>,
    head: &Arc<Layer>,
    branch: &str,
    name: &str,
    src: &str,
) -> Arc<Layer> {
    let resources = esl::compile(src, head)
        .unwrap_or_else(|e| panic!("{name} compiles against the chain: {e:?}"));
    let mut b = LayerBuilder::new(name, Some(Arc::clone(head)));
    for r in resources {
        b.add_resource(r)
            .unwrap_or_else(|e| panic!("{name}: {e:?}"));
    }
    let layer = Arc::new(b.build(LayerStorage::with_persistent(Arc::clone(backend))));
    let persister = BackendPersister::new(Some(Arc::clone(backend)));
    let info = persister.persist(branch, &layer).expect("persist");
    assert!(info.branch_advanced, "{name} advances {branch}");
    layer
}

/// Every validation error the chain at `head` reports about a resource under `urn:eigenius:uab:`,
/// as `(resource IRI, message)`.
fn toy_errors(head: &Arc<Layer>) -> Vec<(String, String)> {
    eigenius_kernel::validation::Validator::new(Arc::clone(head))
        .validate()
        .into_iter()
        .filter_map(|e| {
            let iri = e.resource_id.as_ref()?.as_str().to_string();
            iri.starts_with("urn:eigenius:uab:")
                .then_some((iri, e.message))
        })
        .collect()
}

fn errors_for(errors: &[(String, String)], local: &str) -> Vec<String> {
    let iri = format!("urn:eigenius:uab:residue-variant:{local}");
    errors
        .iter()
        .filter(|(i, _)| *i == iri)
        .map(|(_, m)| m.clone())
        .collect()
}

#[test]
#[ignore = "DB-backed; set EIGENIUS_DB_SNAPSHOT + run --ignored --nocapture"]
fn the_kernel_refuses_the_residue_to_variant_substitution() {
    let Some(snap) = std::env::var("EIGENIUS_DB_SNAPSHOT")
        .ok()
        .map(PathBuf::from)
    else {
        eprintln!("SKIP: EIGENIUS_DB_SNAPSHOT unset");
        return;
    };
    let (base, backend) = match open_head_and_backend(&snap) {
        Ok(x) => x,
        Err(e) => {
            eprintln!("SKIP: {e}");
            return;
        }
    };
    let read = |file: &str| {
        std::fs::read_to_string(repo(&format!("experiments/residue-variant/{file}")))
            .unwrap_or_else(|e| panic!("{file} reads: {e}"))
    };

    // The vocabulary, the definition over the parse, the bridge, the parsed claims, the conclusions.
    let mut head = base;
    for (name, file) in [
        ("avpr2", "avpr2.esl"),
        ("survey-typed", "survey-typed.esl"),
        ("bridge", "bridge.esl"),
        ("claims", "claims.esl"),
    ] {
        head = load_layer(&backend, &head, "main", name, &read(file));
    }
    let shared = Arc::clone(&head);
    let conclusions = load_layer(
        &backend,
        &shared,
        "main",
        "conclusions",
        &read("conclusions.esl"),
    );
    let errors = toy_errors(&conclusions);
    for (iri, m) in &errors {
        eprintln!("{iri}: {m}");
    }

    // A and B must be refused for THEIR reasons. A certificate that fails to decode is refused too,
    // and for nothing the toy is about — the reason is what the test checks.
    let a = errors_for(&errors, "concl_leu44").join("\n");
    assert!(
        a.contains("does not inhabit class urn:eigenius:uab:avpr2:Variant"),
        "A: DDAVPResponsive(Leu44) must be refused because Leu44 is not a Variant; got:\n{a}"
    );
    let b = errors_for(&errors, "concl_c131").join("\n");
    assert!(
        b.contains(
            "no admitted IsDeclaredAs witness for IRI urn:eigenius:uab:residue-variant:claim_1"
        ),
        "B: DDAVPResponsive(c.131T>C) must be refused because the survey sentence grounds nothing \
         about c.131T>C; got:\n{b}"
    );
    let c = errors_for(&errors, "concl_survey");
    assert!(
        c.is_empty(),
        "C: the survey sentence, cited for what it says, must commit; got:\n{}",
        c.join("\n")
    );
    // Nothing else the toy committed is in error — the vocabulary, the definition, the bridge and
    // the claims all pass the validator.
    let rest: Vec<_> = errors
        .iter()
        .filter(|(i, _)| !i.ends_with(":concl_leu44") && !i.ends_with(":concl_c131"))
        .collect();
    assert!(rest.is_empty(), "unexpected validation errors: {rest:#?}");

    // D: the declared inverse of HasResidue, on its own branch.
    backend
        .put_branch("residue-bridge", shared.id())
        .expect("point residue-bridge at the shared head");
    let inverse = load_layer(
        &backend,
        &shared,
        "residue-bridge",
        "residue-bridge",
        &read("residue-bridge.esl"),
    );
    let errors = toy_errors(&inverse);
    for (iri, m) in &errors {
        eprintln!("{iri}: {m}");
    }
    assert!(
        errors.is_empty(),
        "D: with the inverse declared, the substitution commits; got: {errors:#?}"
    );
}
