// Copyright 2026 The Eigenius Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Fixture-shape regression for the lean-verification notebook demo.
//!
//! Loads `notebooks/examples/lean-verification-demo.eigon.json`
//! (regenerated by `cargo run -p eigenius-lean --example
//! gen_verification_demo`) through the **same commit-pipeline shape
//! `eigenius load` takes** — the D41 commit orchestrator running a
//! `WithInstitutions` pipeline — so this test catches every failure
//! mode the live notebook setup would hit:
//!
//! - **Validator violations** (missing required properties on
//!   `RuntimePackageMirror` etc.) surface as
//!   `CommitError::Validation` *before* AutoOnLoad fires. An earlier
//!   version of the test used `LayerBuilder::build()` directly and
//!   missed a class of bugs the validator catches at commit time but
//!   the in-memory builder skips. This shape pins that gap closed.
//! - **AutoOnLoad failure** — `qc_proof_check` returning Fails or the
//!   institution-side handler erroring surfaces as a non-Holds verdict
//!   in the rescued `verdict_provenance` Sibling layer (D41 §3.4 / §6.1).
//! - **Anchor/correspondence drift** — a fixture whose
//!   `library_content_hash`, `source_layer`, or `mirrored_classes`
//!   doesn't match what the proof + claim demand surfaces as a
//!   non-Holds verdict.
//!
//! D41 §10: the test invokes [`CommitOrchestrator`] directly with the
//! `WithInstitutions` pipeline kind, mirroring the Load handler's
//! shape in `kernel/src/server/mod.rs` minus the gRPC plumbing. The
//! orchestrator's `verdict_provenance` `Sibling` emission is the chain
//! position the demo's Verdict lands on; we inspect the orchestrator
//! outcome's `layers` array for it after the drain.
//!
//! Reads a ~675 KB fixture and has nanoda re-check the capstone proof, and runs in a few
//! seconds — it is NOT `#[ignore]`d. It was, and a real failure sat behind the annotation
//! unnoticed (eigenius#207): the gate stopped being about cost and started hiding a
//! regression. This is the only test that puts a `lean:proposition` through the validator,
//! so it is the one that catches a shape change in the chain mirror.

use std::path::PathBuf;
use std::sync::Arc;

use eigenius_kernel::commit::{
    BackendPersister, CommitOrchestrator, CommitWorkingSetPool, EmissionKind, InstitutionContext,
    LayerEmission, LayerRole, NoopHost, PipelineKind,
};
use eigenius_kernel::context::{ExecutionContext, ExecutionMode};
use eigenius_kernel::institution::registry::InstitutionIndex;
use eigenius_kernel::institution::runtime::{Institution, InstitutionRuntime};
use eigenius_kernel::lattice::CommitPolicy;
use eigenius_kernel::layer::{Layer, LayerStorage};
use eigenius_kernel::ontology::eigon_json;
use eigenius_kernel::ontology::iri::Iri;
use eigenius_kernel::ontology::resource::Value;
use eigenius_kernel::ontology::well_known as wk;
use eigenius_kernel::storage::memory::MemoryPersistentBackend;
use eigenius_kernel::storage::PersistentBackend;

use eigenius_lean::LeanInstitution;

const DEMO_PROOF_TERM_IRI: &str = "urn:eigenius:demo:lean:proof_term";
const VERDICT_SUBJECT_PROP: &str = "urn:eigenius:institution:verdict_subject";
const VERDICT_CLASS_IRI: &str = "urn:eigenius:institution:Verdict";

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .map(|root| {
            root.join("notebooks")
                .join("examples")
                .join("lean-verification-demo.eigon.json")
        })
        .expect("workspace root must have two ancestor segments from this crate")
}

/// The committed fixture's resources.
fn fixture_resources() -> Vec<eigenius_kernel::ontology::resource::Resource> {
    let path = fixture_path();
    let bytes = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "read notebook demo fixture `{}`: {e}\n\
             Regenerate via: cargo run -p eigenius-lean --example gen_verification_demo",
            path.display()
        )
    });
    let resources = eigon_json::parse_document(&bytes).unwrap_or_else(|e| {
        panic!(
            "parse demo fixture `{}` as Eigon-JSON: {e:?}",
            path.display()
        )
    });
    assert_eq!(
        resources.len(),
        6,
        "demo fixture must carry exactly six resources (Patient class, the `Healthy` axiom its \
         proposition applies, the claim instance, mirror, payload, term); got {}",
        resources.len()
    );
    resources
}

/// Drive the commit orchestrator over `resources`, exactly as the Load handler does.
fn land(
    resources: Vec<eigenius_kernel::ontology::resource::Resource>,
) -> eigenius_kernel::commit::MultiLayerOutcome {
    // Bootstrap the chain on a memory-backed `PersistentBackend` so
    // the orchestrator's persist phase has somewhere to land layers.
    // The `WithInstitutions` pipeline runs `autoonload_dispatch`,
    // which queues a `verdict_provenance` Sibling emission; the
    // orchestrator drains it after the user-layer persist (or rescues
    // it on the Fails path). Both arms require an actual backend.
    let backend = Arc::new(MemoryPersistentBackend::new());
    let storage = LayerStorage::with_persistent(Arc::clone(&backend) as Arc<dyn PersistentBackend>);
    let bootstrap_ctx = eigenius_kernel::bootstrap::bootstrap_with_storage(storage.clone())
        .expect("bootstrap with memory backend");
    let head = Arc::clone(bootstrap_ctx.head());

    // Seed the `main` ref at the bootstrap head. `BackendPersister`'s CAS passes
    // `expected_old = layer.parent().id()`; against a store where `main` was never written the
    // ref reads as the zero LayerId, the CAS mismatches, and the commit comes back
    // `NeedsWitnessedMerge` with `branch_advanced: false` — which silently drops the Sibling.
    // A server writes this ref when it bootstraps a fresh store; the test bootstraps its own.
    backend
        .put_branch("main", head.id())
        .expect("seed the main branch ref at the bootstrap head");

    let (index, errors) = InstitutionIndex::from_layer(&head);
    assert!(
        errors.is_empty(),
        "InstitutionIndex over bootstrap must build cleanly; got {errors:?}"
    );
    let index = Arc::new(index);

    let mut runtime = InstitutionRuntime::new();
    let lean: Arc<dyn Institution> = LeanInstitution::arc();
    runtime
        .register(Box::new(Arc::clone(&lean)))
        .expect("register LeanInstitution");
    let runtime = Arc::new(runtime);

    // Build an execution context the same way the CLI does for
    // `eigenius load`: read-write mode, working layer on top of the
    // bootstrap head. Adding resources stages them in the working
    // layer; `take_working` then hands the builder off to the commit
    // orchestrator as the root `LayerEmission`. The
    // `WithInstitutions` pipeline runs structural validation, the D31
    // §5 install-time cross-check (via `autoonload_dispatch`'s
    // pre-conditions), and AutoOnLoad dispatch into the LeanInstitution.
    let mut ctx = ExecutionContext::new(
        head,
        "notebook_demo_fixture",
        ExecutionMode::ReadWrite,
        storage,
    );
    for r in resources {
        ctx.add_resource(r)
            .expect("add fixture resource to execution context");
    }

    // Drive the commit orchestrator the way the Load handler does
    // (kernel/src/server/mod.rs §2190), through the same persister the
    // gRPC service holds: `BackendPersister` owns the anchored-commit
    // cache probe and the branch CAS.
    //
    // The lattice-side `BackendStorePersister` cannot stand in here. It
    // is `store_layer`-only and reports `branch_advanced: false`
    // unconditionally, and the orchestrator drops a landed layer's
    // emissions when its parent did not advance the branch
    // (`orchestrator.rs` §6.4). Under that persister the
    // `verdict_provenance` Sibling is queued and then discarded, so the
    // assertion below could never hold however the demo verified.
    //
    // `NoopHost` satisfies `CommitHookHost` without needing the
    // server's index-rebuild / vector-sweep machinery; the test cares
    // about AutoOnLoad's `verdict_provenance` Sibling.
    let working = ctx
        .take_working("notebook_demo_fixture")
        .expect("take_working");
    let root = LayerEmission::from_builder(
        LayerRole::User,
        "notebook_demo_fixture",
        PipelineKind::WithInstitutions,
        EmissionKind::Child,
        working,
    );
    let persister = BackendPersister::new(Some(Arc::clone(&backend) as Arc<dyn PersistentBackend>));
    let host = NoopHost;
    let pool = CommitWorkingSetPool::in_memory();
    {
        let orchestrator = CommitOrchestrator {
            ctx: &mut ctx,
            pool: &pool,
            persister: &persister,
            host: &host,
            branch: "main",
            policy: CommitPolicy::default(),
            institutions: Some(InstitutionContext {
                index: Arc::clone(&index),
                runtime: Arc::clone(&runtime),
                _marker: std::marker::PhantomData,
            }),
            did_drain: CommitOrchestrator::default_did_drain(),
        };
        orchestrator.run(root)
    }
}

#[test]
fn notebook_demo_fixture_lands_holds() {
    let outcome = land(fixture_resources());

    // On the all-Ok / Holds path the orchestrator returns
    // `outcome.error = None` and the layers vector carries the user
    // layer at index 0 and the `verdict_provenance` Sibling at index
    // 1. The Sibling is what carries the AutoOnLoad verdicts; the
    // user-layer carries the demo's authored resources.
    assert!(
        outcome.error.is_none(),
        "orchestrator should land the demo cleanly; got error: {:?}",
        outcome.error
    );
    assert!(
        outcome.layers.len() >= 2,
        "WithInstitutions pipeline must land at least the user layer + \
         verdict_provenance Sibling; got {} layers",
        outcome.layers.len()
    );
    let provenance: Arc<Layer> = Arc::clone(&outcome.layers[1].layer);

    // Walk the provenance layer for a Verdict resource whose
    // `verdict_subject` is the demo proof term, and assert
    // `ctor_name = \"Holds\"`. This is the same shape the notebook's
    // first EigenQL query exercises.
    let term_iri = Iri::parse(DEMO_PROOF_TERM_IRI).expect("static IRI must parse");
    let subject_prop = Iri::parse(VERDICT_SUBJECT_PROP).expect("static IRI must parse");
    let ctor_name_prop = Iri::parse(wk::CTOR_NAME).expect("static IRI must parse");
    let verdict_class_iri = Iri::parse(VERDICT_CLASS_IRI).expect("static IRI must parse");

    let mut matched_ctor: Option<String> = None;
    for (_iri, r) in provenance.iter_resources() {
        let is_verdict = r.is_a().iter().any(|c| c.as_str() == VERDICT_CLASS_IRI)
            || r.is_a()
                .iter()
                .any(|c| c.as_str() == verdict_class_iri.as_str());
        if !is_verdict {
            continue;
        }
        let subject_match = r
            .get(&subject_prop)
            .map(|v| match v {
                Value::String(iri) => iri.as_str() == term_iri.as_str(),
                _ => false,
            })
            .unwrap_or(false);
        if !subject_match {
            continue;
        }
        if let Some(Value::String(c)) = r.get(&ctor_name_prop) {
            matched_ctor = Some(c.clone());
            break;
        }
    }

    let ctor = matched_ctor.unwrap_or_else(|| {
        panic!(
            "no Verdict resource found for subject `{DEMO_PROOF_TERM_IRI}` \
             in the AutoOnLoad provenance layer — verdict shape may have drifted"
        )
    });
    assert_eq!(
        ctor, "Holds",
        "demo proof must yield Verdict::Holds (the load-bearing claim of the lean-verification notebook); \
         got `{ctor}`"
    );
}

/// A claim carrying no `reflection:canonical_proposition` is REFUSED, not skipped.
///
/// This is the fix for eigenius#159. Before it, `claim_proposition` returned `None` for such a
/// claim and the institution fell back to the name-level check — "a theorem called `target_name`
/// type-checks" — which is the verdict that issue opened against. The demo itself demonstrated
/// the hole: its claim carried only `is_a`, so it landed `Holds` with the statement check never
/// running.
///
/// The claim now carries `∀ (p : Patient), Healthy(p) → Healthy(p)`, and stripping it must fail
/// the commit rather than quietly weaken what `Holds` attests.
#[test]
fn a_claim_without_a_proposition_is_refused() {
    use eigenius_kernel::ontology::iri::Iri;
    use eigenius_kernel::ontology::well_known as wk;

    let stripped: Vec<_> = fixture_resources()
        .into_iter()
        .map(|mut r| {
            if r.id().is_some_and(|i| i.as_str().ends_with(":patient_1")) {
                r.remove(&Iri::parse(wk::CANONICAL_PROPOSITION).expect("well-known IRI"));
            }
            r
        })
        .collect();

    let outcome = land(stripped);
    let err = outcome
        .error
        .expect("a claim with no proposition must not land");
    let msg = format!("{err:?}");
    assert!(
        msg.contains("canonical_proposition"),
        "the refusal must name what is missing; got {msg}"
    );
    assert!(
        msg.contains("target name alone") || msg.contains("nothing to check"),
        "and must say why a name-level verdict is not enough; got {msg}"
    );
}

/// A `Verdict::Holds` reaches the **verified** grade — the whole of eigenius#160.
///
/// Before this, `do_proof_check` returned a Verdict and nothing else, so a checked Lean proof
/// left the chain in the same state a failed one did. `verified(X)` in a justification term was
/// unsatisfiable by any Lean proof, and D28 §1's reason for the institution to exist was not
/// wired end to end.
///
/// Three things have to hold together, and the test asserts each separately because any one of
/// them failing alone would leave the other two looking correct:
///
/// 1. the institution emits a `prov:VerificationTrace` pointing at the claim;
/// 2. the kernel does **not** stamp `reflection:InstitutionEmittedDerivation` on it — that class
///    says "grounds nothing", which is the opposite of what a trace is for;
/// 3. `lookup_chain_witness` answers `true` for `Verified` on the claim's own proposition. This
///    is the one that matters: (1) and (2) are how it is reached, not what it delivers.
#[test]
fn a_holds_verdict_admits_a_verified_witness() {
    use eigenius_kernel::layer::lookup_chain_witness;
    use eigenius_kernel::witness::{WitnessCategory, WitnessKey};

    const CLAIM_IRI: &str = "urn:eigenius:demo:lean:patient_1";
    const PAYLOAD_IRI: &str = "urn:eigenius:demo:lean:proof_payload";

    let resources = fixture_resources();
    let claim_proposition = resources
        .iter()
        .find(|r| r.id().is_some_and(|i| i.as_str() == CLAIM_IRI))
        .and_then(|r| r.get(&Iri::parse(wk::CANONICAL_PROPOSITION).expect("well-known IRI")))
        .expect("the demo claim carries a canonical_proposition (eigenius#159)")
        .clone();

    let outcome = land(resources);
    assert!(
        outcome.error.is_none(),
        "the demo must land cleanly; got {:?}",
        outcome.error
    );
    let provenance: Arc<Layer> = Arc::clone(&outcome.layers[1].layer);

    // 1. The trace is there, and it names the claim rather than the proof term. `prov:resource`
    //    is what `emit_from_trace` follows to find the proposition the witness keys on, so a
    //    trace pointing at the `LeanProofTerm` would commit cleanly and attest nothing.
    let trace = provenance
        .iter_resources()
        .map(|(_, r)| r)
        .find(|r| {
            r.is_a()
                .iter()
                .any(|c| c.as_str() == wk::VERIFICATION_TRACE)
        })
        .expect("a Holds verdict must commit a prov:VerificationTrace beside it");
    assert_eq!(
        trace.get(&Iri::parse(wk::REFLECTION_RESOURCE).expect("well-known IRI")),
        Some(&Value::iri(&Iri::parse(CLAIM_IRI).expect("static IRI"))),
        "the trace must target the CLAIM — that is where the proposition the witness keys on lives"
    );
    assert_eq!(
        trace
            .get(&Iri::parse(wk::PROOF_SYSTEM).expect("well-known IRI"))
            .and_then(Value::as_str),
        Some("lean4"),
    );
    assert_eq!(
        trace
            .get(&Iri::parse(wk::PROOF_TERM).expect("well-known IRI"))
            .and_then(Value::as_str),
        Some(PAYLOAD_IRI),
        "prov:proof_term names the resource holding the export bytes"
    );

    // 2. No "grounds nothing" marker on the one resource whose purpose is to be a ground.
    assert!(
        !trace
            .is_a()
            .iter()
            .any(|c| c.as_str() == wk::INSTITUTION_EMITTED_DERIVATION),
        "finalize_emitted_resource must withhold the derivation marker from a prov:Trace; got {:?}",
        trace.is_a()
    );

    // 3. The grade itself.
    let key = WitnessKey::from_encoded(
        WitnessCategory::Verified,
        Iri::parse(CLAIM_IRI).expect("static IRI"),
        &claim_proposition,
    );
    assert!(
        lookup_chain_witness(&provenance, &key),
        "the chain must admit `Verified` for the claim's own proposition — this is the grade the \
         Lean institution exists to reach (D28 §1 / eigenius#160)"
    );
}
