[package]
name = "eigenius-wasm-d14-arrhenius"
version = "0.1.0"
edition = "2021"

[dependencies]
eigenius-wasm-sdk = { path = "../../sdk/wasm-sdk" }
wit-bindgen = "0.57"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "eigenius:component"

[package.metadata.component.target]
world = "eigenius-component"
path = "../../wit"
