// Copyright 2026 The Eigenius Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Locate and load the napi-rs native addon built from
 * `orchestration/runtime-substrate-native/`.
 *
 * Mirrors `wasm/loadAddon.ts`: the addon's `index.js` + `index.d.ts`
 * are generated by `napi build --platform`. We require `index.js`
 * through Node's CJS shim so Deno's Node-compat layer resolves the
 * underlying `.node` file for the platform.
 *
 * Run with Deno flags:
 *   --allow-ffi --allow-env --allow-sys --unstable-node-globals --unstable-detect-cjs
 */

import { createRequire } from "node:module";
import * as log from "../observability/mod.ts";
import { operation } from "../observability/mod.ts";

export interface RuntimeSubstrateAddon {
  /** Register the bash-c TestLanguageRuntime under language_id="test".
   * `workerBinaryPath` must point at the substrate crate's
   * `eigenius-test-worker` binary (e.g. `target/debug/eigenius-test-worker`). */
  registerTestLanguageRuntime(workerBinaryPath: string): void;

  /** Dispatch a `RunRuntimeScript` invocation. Both args are
   * Eigon-CBOR `Buffer`s; returns the output Resource as Eigon-CBOR. */
  dispatchRunRuntimeScript(
    input: Uint8Array,
    argument: Uint8Array,
  ): Promise<Uint8Array>;

  /** Dispatch a `CallRuntimeMethod` invocation. v1 errors against any
   * `JobSpawner`-backed runtime — service-lifecycle envs land in
   * Phase 19a. */
  dispatchCallRuntimeMethod(
    input: Uint8Array,
    argument: Uint8Array,
  ): Promise<Uint8Array>;

  /** Language IDs of currently-registered runtimes. */
  listRegisteredLanguages(): string[];
}

let cached: RuntimeSubstrateAddon | undefined;

/**
 * Load the native addon. Idempotent within a process.
 *
 * Throws a helpful error if the addon isn't built. The expected binary
 * lives at `orchestration/runtime-substrate-native/index.js` relative
 * to the repo root. Build it with
 * `(cd orchestration/runtime-substrate-native && ./node_modules/.bin/napi build --platform)`.
 */
export function loadRuntimeSubstrateAddon(): RuntimeSubstrateAddon {
  if (cached) return cached;

  const require = createRequire(import.meta.url);
  const addonUrl = new URL(
    "../../runtime-substrate-native/index.js",
    import.meta.url,
  );

  try {
    cached = require(addonUrl.pathname) as RuntimeSubstrateAddon;
    return cached;
  } catch (e) {
    throw new Error(
      `Failed to load runtime substrate addon at ${addonUrl.pathname}. ` +
        `Build it with: ` +
        `(cd orchestration/runtime-substrate-native && ./node_modules/.bin/napi build --platform). ` +
        `Underlying error: ${(e as Error).message}`,
    );
  }
}

/**
 * Attempt to load the addon, returning null if it isn't built. Used by
 * the orchestrator at startup so we can run without substrate support
 * — `RunRuntimeScript` / `CallRuntimeMethod` dispatches then fail with
 * a clear "no handler registered" error instead of crashing the server.
 */
export function tryLoadRuntimeSubstrateAddon(): RuntimeSubstrateAddon | null {
  try {
    return loadRuntimeSubstrateAddon();
  } catch (e) {
    log.warn(
      operation.WASM_ADDON_LOAD,
      "runtime substrate addon unavailable",
      {
        error_kind: "addon_load_failed",
        error_message: (e as Error).message.split("\n")[0],
      },
    );
    return null;
  }
}
