// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type ResourceData = eigenius::component::types::ResourceData;
pub type ValidationResult = eigenius::component::institution_types::ValidationResult;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_fiber_declaration_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::fiber_declaration();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec2 = (result0).into_boxed_slice();
    let ptr2 = vec2.as_ptr().cast::<u8>();
    let len2 = vec2.len();
    ::core::mem::forget(vec2);
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_fiber_declaration<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base2 = l0;
    let len2 = l1;
    _rt::cabi_dealloc(base2, len2 * 1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_query_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let result1 = T::query(_rt::Vec::from_raw_parts(arg0.cast(), len0, len0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
        Ok(e) => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
            let vec3 = (e).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3
                .cast_mut();
        }
        Err(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let vec4 = (e.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
                .cast_mut();
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_query<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base3 = l1;
            let len3 = l2;
            _rt::cabi_dealloc(base3, len3 * 1, 1);
        }
        _ => {
            let l4 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l5 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l4, l5, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_validate_morphism_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let result1 = T::validate_morphism(
        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
    );
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
        Ok(e) => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
            let (t3_0, t3_1) = e;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (t3_0.clone()
                as i32) as u8;
            let vec4 = (t3_1.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
                .cast_mut();
        }
        Err(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let vec5 = (e.into_bytes()).into_boxed_slice();
            let ptr5 = vec5.as_ptr().cast::<u8>();
            let len5 = vec5.len();
            ::core::mem::forget(vec5);
            *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5
                .cast_mut();
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_validate_morphism<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l2 = *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
        _ => {
            let l3 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l4 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_discover_morphisms_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let base3 = arg0;
    let len3 = arg1;
    let mut result3 = _rt::Vec::with_capacity(len3);
    for i in 0..len3 {
        let base = base3.add(i * (2 * ::core::mem::size_of::<*const u8>()));
        let e3 = {
            let l0 = *base.add(0).cast::<*mut u8>();
            let l1 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len2 = l1;
            _rt::Vec::from_raw_parts(l0.cast(), len2, len2)
        };
        result3.push(e3);
    }
    _rt::cabi_dealloc(
        base3,
        len3 * (2 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result4 = T::discover_morphisms(result3);
    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result4 {
        Ok(e) => {
            *ptr5.add(0).cast::<u8>() = (0i32) as u8;
            let vec7 = e;
            let len7 = vec7.len();
            let layout7 = _rt::alloc::Layout::from_size_align_unchecked(
                vec7.len() * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result7 = if layout7.size() != 0 {
                let ptr = _rt::alloc::alloc(layout7).cast::<u8>();
                if ptr.is_null() {
                    _rt::alloc::handle_alloc_error(layout7);
                }
                ptr
            } else {
                ::core::ptr::null_mut()
            };
            for (i, e) in vec7.into_iter().enumerate() {
                let base = result7.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                {
                    let vec6 = (e).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *base.add(0).cast::<*mut u8>() = ptr6.cast_mut();
                }
            }
            *ptr5.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
            *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result7;
        }
        Err(e) => {
            *ptr5.add(0).cast::<u8>() = (1i32) as u8;
            let vec8 = (e.into_bytes()).into_boxed_slice();
            let ptr8 = vec8.as_ptr().cast::<u8>();
            let len8 = vec8.len();
            ::core::mem::forget(vec8);
            *ptr5.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
            *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr8
                .cast_mut();
        }
    };
    ptr5
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_discover_morphisms<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base6 = l1;
            let len6 = l2;
            for i in 0..len6 {
                let base = base6.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                {
                    let l3 = *base.add(0).cast::<*mut u8>();
                    let l4 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base5 = l3;
                    let len5 = l4;
                    _rt::cabi_dealloc(base5, len5 * 1, 1);
                }
            }
            _rt::cabi_dealloc(
                base6,
                len6 * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
        }
        _ => {
            let l7 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l8 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l7, l8, 1);
        }
    }
}
pub trait Guest {
    /// Declare this institution's fiber structure.
    /// Returns a CBOR-encoded FiberDeclaration resource.
    fn fiber_declaration() -> ResourceData;
    /// Execute a fiber query.
    fn query(q: ResourceData) -> Result<ResourceData, _rt::String>;
    /// Validate a morphism resource.
    /// Returns the validation result; on Invalid, the optional string is the reason.
    fn validate_morphism(
        morphism: ResourceData,
    ) -> Result<(ValidationResult, _rt::String), _rt::String>;
    /// Discover morphisms between a set of resources.
    /// Returns a list of new morphism resources (CBOR-encoded).
    fn discover_morphisms(
        resources: _rt::Vec<ResourceData>,
    ) -> Result<_rt::Vec<ResourceData>, _rt::String>;
}
#[doc(hidden)]
macro_rules! __export_world_eigenius_institution_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "fiber-declaration")] unsafe extern "C"
        fn export_fiber_declaration() -> * mut u8 { unsafe { $($path_to_types)*::
        _export_fiber_declaration_cabi::<$ty > () } } #[unsafe (export_name =
        "cabi_post_fiber-declaration")] unsafe extern "C" fn
        _post_return_fiber_declaration(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_fiber_declaration::<$ty > (arg0) } } #[unsafe (export_name =
        "query")] unsafe extern "C" fn export_query(arg0 : * mut u8, arg1 : usize,) -> *
        mut u8 { unsafe { $($path_to_types)*:: _export_query_cabi::<$ty > (arg0, arg1) }
        } #[unsafe (export_name = "cabi_post_query")] unsafe extern "C" fn
        _post_return_query(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_query::<$ty > (arg0) } } #[unsafe (export_name =
        "validate-morphism")] unsafe extern "C" fn export_validate_morphism(arg0 : * mut
        u8, arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_validate_morphism_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "cabi_post_validate-morphism")] unsafe extern "C" fn
        _post_return_validate_morphism(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_validate_morphism::<$ty > (arg0) } } #[unsafe (export_name =
        "discover-morphisms")] unsafe extern "C" fn export_discover_morphisms(arg0 : *
        mut u8, arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_discover_morphisms_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "cabi_post_discover-morphisms")] unsafe extern "C" fn
        _post_return_discover_morphisms(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_discover_morphisms::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_eigenius_institution_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 4 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 4 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod eigenius {
    pub mod component {
        /// Types shared across all extension interfaces.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// A CBOR-encoded Eigon resource.
            pub type ResourceData = _rt::Vec<u8>;
            /// A CBOR-encoded Mini-TT typed value (D14 §11). Distinct from
            /// `resource-data` even though the wire form is the same: a typed
            /// value inhabits a Mini-TT type (primitive, tuple, inductive,
            /// codata) and is the payload exchanged between the source-side
            /// extract, the Component middle, and the target-side reify.
            pub type TypedValue = _rt::Vec<u8>;
            /// An IRI string.
            pub type Iri = _rt::String;
            /// Result of a component execution.
            #[derive(Clone)]
            pub struct ComponentResult {
                /// CBOR-encoded output resource.
                pub output: ResourceData,
            }
            impl ::core::fmt::Debug for ComponentResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ComponentResult")
                        .field("output", &self.output)
                        .finish()
                }
            }
        }
        /// Types specific to institution hosting.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod institution_types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            /// Result of morphism validation.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum ValidationResult {
                Valid,
                Invalid,
                Undecidable,
            }
            impl ::core::fmt::Debug for ValidationResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        ValidationResult::Valid => {
                            f.debug_tuple("ValidationResult::Valid").finish()
                        }
                        ValidationResult::Invalid => {
                            f.debug_tuple("ValidationResult::Invalid").finish()
                        }
                        ValidationResult::Undecidable => {
                            f.debug_tuple("ValidationResult::Undecidable").finish()
                        }
                    }
                }
            }
            impl ValidationResult {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> ValidationResult {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => ValidationResult::Valid,
                        1 => ValidationResult::Invalid,
                        2 => ValidationResult::Undecidable,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
        }
        /// Read-only access to the knowledge graph.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod read_access {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type ResourceData = super::super::super::eigenius::component::types::ResourceData;
            pub type Iri = super::super::super::eigenius::component::types::Iri;
            #[allow(unused_unsafe, clippy::all)]
            /// Resolve a resource by IRI from the layer chain.
            pub fn resolve(iri: &str) -> Option<ResourceData> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = iri;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "eigenius:component/read-access@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "resolve"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result7 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                _rt::Vec::from_raw_parts(l4.cast(), len6, len6)
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result7
                }
            }
        }
        /// Query access to the knowledge graph.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod query_access {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type ResourceData = super::super::super::eigenius::component::types::ResourceData;
            #[allow(unused_unsafe, clippy::all)]
            /// Execute an EigenQL query.
            pub fn query(eigenql: &str) -> Result<_rt::Vec<ResourceData>, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = eigenql;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "eigenius:component/query-access@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "query"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result13 = match l3 {
                        0 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base9 = l4;
                                let len9 = l5;
                                let mut result9 = _rt::Vec::with_capacity(len9);
                                for i in 0..len9 {
                                    let base = base9
                                        .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                    let e9 = {
                                        let l6 = *base.add(0).cast::<*mut u8>();
                                        let l7 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len8 = l7;
                                        _rt::Vec::from_raw_parts(l6.cast(), len8, len8)
                                    };
                                    result9.push(e9);
                                }
                                _rt::cabi_dealloc(
                                    base9,
                                    len9 * (2 * ::core::mem::size_of::<*const u8>()),
                                    ::core::mem::size_of::<*const u8>(),
                                );
                                result9
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l10 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l11 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len12 = l11;
                                let bytes12 = _rt::Vec::from_raw_parts(
                                    l10.cast(),
                                    len12,
                                    len12,
                                );
                                _rt::string_lift(bytes12)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result13
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_eigenius_institution_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_eigenius_institution_cabi!($ty
        with_types_in $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_eigenius_institution_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:eigenius:component@0.1.0:eigenius-institution:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 876] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe1\x05\x01A\x02\x01\
A\x1b\x01B\x08\x01p}\x04\0\x0dresource-data\x03\0\0\x01p}\x04\0\x0btyped-value\x03\
\0\x02\x01s\x04\0\x03iri\x03\0\x04\x01r\x01\x06output\x01\x04\0\x10component-res\
ult\x03\0\x06\x03\0\x1eeigenius:component/types@0.1.0\x05\0\x02\x03\0\0\x0dresou\
rce-data\x03\0\x0dresource-data\x03\0\x01\x02\x03\0\0\x03iri\x03\0\x03iri\x03\0\x03\
\x01B\x02\x01m\x03\x05valid\x07invalid\x0bundecidable\x04\0\x11validation-result\
\x03\0\0\x03\0*eigenius:component/institution-types@0.1.0\x05\x05\x02\x03\0\x01\x11\
validation-result\x03\0\x11validation-result\x03\0\x06\x01B\x07\x02\x03\x02\x01\x01\
\x04\0\x0dresource-data\x03\0\0\x02\x03\x02\x01\x03\x04\0\x03iri\x03\0\x02\x01k\x01\
\x01@\x01\x03iri\x03\0\x04\x04\0\x07resolve\x01\x05\x03\0$eigenius:component/rea\
d-access@0.1.0\x05\x08\x01B\x06\x02\x03\x02\x01\x01\x04\0\x0dresource-data\x03\0\
\0\x01p\x01\x01j\x01\x02\x01s\x01@\x01\x07eigenqls\0\x03\x04\0\x05query\x01\x04\x03\
\0%eigenius:component/query-access@0.1.0\x05\x09\x01@\0\0\x02\x04\0\x11fiber-dec\
laration\x01\x0a\x01j\x01\x02\x01s\x01@\x01\x01q\x02\0\x0b\x04\0\x05query\x01\x0c\
\x01o\x02\x07s\x01j\x01\x0d\x01s\x01@\x01\x08morphism\x02\0\x0e\x04\0\x11validat\
e-morphism\x01\x0f\x01p\x02\x01j\x01\x10\x01s\x01@\x01\x09resources\x10\0\x11\x04\
\0\x12discover-morphisms\x01\x12\x04\0-eigenius:component/eigenius-institution@0\
.1.0\x04\0\x0b\x1a\x01\0\x14eigenius-institution\x03\0\0\0G\x09producers\x01\x0c\
processed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
