/**
 * Locate and load the napi-rs native addon built from `orchestration/native/`.
 *
 * The addon exports are generated by the napi-rs CLI into an `index.js` +
 * `index.d.ts` pair. We require `index.js` through Node's CJS shim so Deno's
 * Node-compat layer resolves the underlying `.node` file for the platform.
 *
 * Run with Deno flags:
 *   --allow-ffi --allow-env --allow-sys --unstable-node-globals --unstable-detect-cjs
 */

import { createRequire } from "node:module";

export interface WasmAddon {
  loadComponent(
    binary: Uint8Array,
    opts: { fuelLimit: number; memoryLimitPages: number },
  ): Promise<number>;

  unloadComponent(handle: number): boolean;

  executeComponent(
    handle: number,
    input: Uint8Array,
    argument: Uint8Array,
    dispatch: (
      iri: string,
      input: Uint8Array,
      argument: Uint8Array,
    ) => Promise<Uint8Array>,
    resolve: (iri: string) => Promise<Uint8Array | null>,
    query: (eigenql: string) => Promise<Uint8Array[]>,
  ): Promise<Uint8Array>;
}

let cached: WasmAddon | undefined;

/**
 * Load the native addon. Idempotent within a process.
 *
 * Throws a helpful error if the addon isn't built. The expected binary lives
 * at `orchestration/native/index.js` relative to the repo root. Build it
 * with `./node_modules/.bin/napi build --platform` from that directory.
 */
export function loadWasmAddon(): WasmAddon {
  if (cached) return cached;

  const require = createRequire(import.meta.url);
  const addonUrl = new URL("../../native/index.js", import.meta.url);

  try {
    // The napi-rs-generated index.js uses `require` internally to load the
    // .node file. Deno resolves this through its Node-compat layer.
    cached = require(addonUrl.pathname) as WasmAddon;
    return cached;
  } catch (e) {
    throw new Error(
      `Failed to load native WASM addon at ${addonUrl.pathname}. ` +
        `Build it with: (cd orchestration/native && ./node_modules/.bin/napi build --platform). ` +
        `Underlying error: ${(e as Error).message}`,
    );
  }
}

/**
 * Attempt to load the addon, returning null if it isn't built. Used by the
 * orchestrator at startup so we can run without WASM support — any
 * `RegisterWasmComponent` RPC will then fail with a clear error instead
 * of crashing the server.
 */
export function tryLoadWasmAddon(): WasmAddon | null {
  try {
    return loadWasmAddon();
  } catch (e) {
    console.warn(
      `[wasm] native addon unavailable: ${(e as Error).message.split("\n")[0]}`,
    );
    return null;
  }
}
