// Copyright 2026 The Eigenius Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Structural size comparison for sized types (Phase 11b, D19 §8).
//!
//! **Sized types exist for codata productivity first.** D19's decisions table: *"Sized types? In
//! scope (#16) | Required for complete termination story when combining inductive recursion with
//! codata corecursion"* (D19:491). A sized codata type's observations use `SizedPi` for their
//! recursive occurrences, and `check`'s `(Exp::Lam, Val::SizedPi)` arm opens the size binder and
//! registers `j < upper` in the TSO — so a corecord's observations are forced BY TYPE to produce
//! at sizes strictly below the outer one (`check/codata.rs:783-791`, Phase 11b step 15f). Sized
//! inductives are the other half of that story: a recursive call type-checks only at a strictly
//! smaller size (D19 §8.4). `check_guarded` (`check/codata.rs:189`, D11 §3) is the weaker unsized
//! companion, and its own doc names the gap sized types close.
//!
//! This module supplies the comparison that all of that rests on — `size_le` / `size_lt`, and the
//! `_with_hyps` forms that consult the rigid-hypothesis TSO in [`crate::nbe::sized_rigid`]. Four
//! sites use it: the productivity arm above, inductive size-parameter subtyping (`check/conv.rs`),
//! and the bounded size-argument checks in `check/mod.rs` and `check/inductive.rs`.
//!
//! ## What used to be here, and why it is gone (eigenius#139)
//!
//! Roughly 390 lines of this module were a port of MiniAgda's `Warshall.hs` — a min-plus weighted
//! graph, its Floyd–Warshall transitive closure, and least-value extraction for FLEXIBLE size
//! metavariables (`Weight`, `Rigid`, `Node`, `Constraint`, `arc`, `SizeExpr`, `solve`, `Solution`,
//! `Graph`, `warshall`). It was size *inference*, and it never had a caller.
//!
//! Removed `2026-08-22` rather than wired, for the reasons in
//! [`docs/notes/p2-n2-sized-types-wire-or-delete.md`](../../../docs/notes/p2-n2-sized-types-wire-or-delete.md):
//!
//! - **There is nothing to solve for.** `solve` assigns flexible size variables; the term language
//!   has none. A `Val` of size sort is only ever `SizeInf`, `SizeSucc(_)` or a rigid `Neut::Gen`.
//!   Emitters would need size metavariables threaded through `Exp`/`Val`, eval, readback, conv and
//!   the checker BEFORE a single constraint could be emitted.
//! - **Nothing declares a sized type.** `core:Size` is a compiler built-in (`esl/compile.rs`), not
//!   a chain-resident class, and no chain term carries `SizedPi`/`SizeSort`/`SizeInf`/`SizeSucc`.
//! - **The port could not be checked against its source.** The header linked
//!   `references/miniagda/src/Warshall.hs`; that directory does not exist. Unlike the nanoda
//!   citations elsewhere in the kernel, it could not be re-pointed.
//!
//! Productivity does not need it: the `SizedPi` binder carries its upper bound, so sizes are
//! WRITTEN, not inferred. What inference would buy is eliding them — the same ergonomic gain
//! `check/inductive.rs`'s "sized arg cannot be elided" refusal names for inductives.
//!
//! **To revisit**, three things must hold: a chain declares a sized inductive or codata; size
//! metavariables exist in the term language; and MiniAgda is vendored, or the algorithm is
//! re-derived from the paper rather than trusted as a port. The deleted code is in git history.

/// Partial-order comparison on size values: `size_le(s1, s2)` holds
/// iff `s1 ≤ s2` under the size ordering (D19 §8.3).
///
/// The order is generated by three rules:
/// 1. `s ≤ ∞` for every size `s` (infinity is top).
/// 2. `s ≤ ŝ(s')` whenever `s ≤ s'` (successor step).
/// 3. `s ≤ s` — reflexivity on anything the previous rules don't
///    cover, including neutral sizes (size variables / metas).
///
/// Structural `SizeSucc` comparisons unfold on both sides:
/// `ŝ(a) ≤ ŝ(b) ⇐ a ≤ b`. ∞-absorption ensures `ŝ(∞)` never appears
/// as an input — `eval.rs` collapses it — so we don't special-case it.
///
/// Neutral reflexivity is checked by readback equality at level 0.
/// This is conservative — two distinct neutrals are never considered
/// related. Actual entailment between size hypotheses (e.g.
/// `i ≤ ŝ(j)` given `i ≤ j`) is the job of the rigid-hypothesis
/// solver ([`crate::nbe::sized_rigid`]), not this relation.
pub fn size_le(s1: &crate::nbe::val::Val, s2: &crate::nbe::val::Val) -> bool {
    size_le_with_hyps(s1, s2, &crate::nbe::sized_rigid::Tso::new())
}

/// Partial-order comparison on size values, consulting a TSO of rigid
/// hypotheses for neutral-vs-neutral entailment.
///
/// Same rules as [`size_le`] (∞ top, structural, right-step,
/// readback reflexivity), plus one:
///
/// 4. **Hypothesis entailment.** If `s1` normalises to `ŝⁿ r₁` and
///    `s2` to `ŝᵐ r₂` for rigid size vars `r₁, r₂` (represented as
///    `Val::Nt(Gen(level, _))`, where level doubles as rigid-id),
///    and the TSO records `r₁ + k ≤ r₂`, then `size_le` holds iff
///    `n ≤ m + k`. This catches `i ≤ j` when `{i < j}` is in scope
///    as a bounded binder, `ŝ i ≤ j` likewise, etc.
///
/// The TSO is consulted as a last resort: structural rules are
/// always tried first, so callers can pass an empty TSO with no
/// semantic difference from [`size_le`].
pub fn size_le_with_hyps(
    s1: &crate::nbe::val::Val,
    s2: &crate::nbe::val::Val,
    tso: &crate::nbe::sized_rigid::Tso,
) -> bool {
    use crate::nbe::val::Val;
    // Rule 1: anything ≤ ∞.
    if matches!(s2, Val::SizeInf) {
        return true;
    }
    // ∞ ≤ non-∞ cannot hold.
    if matches!(s1, Val::SizeInf) {
        return false;
    }
    // Structural: ŝ(a) ≤ ŝ(b) ⇐ a ≤ b.
    if let (Val::SizeSucc(a), Val::SizeSucc(b)) = (s1, s2) {
        return size_le_with_hyps(a, b, tso);
    }
    // Rule 2 (right-step): s ≤ ŝ(b) ⇐ s ≤ b.
    if let Val::SizeSucc(b) = s2 {
        if size_le_with_hyps(s1, b, tso) {
            return true;
        }
    }
    // Rule 3: readback equality (reflexivity on neutrals etc.).
    let e1 = crate::nbe::readback::readback_val(0, s1);
    let e2 = crate::nbe::readback::readback_val(0, s2);
    if e1 == e2 {
        return true;
    }
    // Rule 4: rigid hypothesis entailment via the TSO.
    if let (Some((n, r1)), Some((m, r2))) = (strip_to_rigid(s1), strip_to_rigid(s2)) {
        if let Some(k) = tso.is_ancestor(r1, r2) {
            // `ŝⁿ r₁ ≤ ŝᵐ r₂` iff `r₁ + n ≤ r₂ + m` iff `n ≤ m + k`.
            if n <= m.saturating_add(k) {
                return true;
            }
        }
    }
    false
}

/// Peel outer `SizeSucc` layers off `v` and, if the core is a neutral
/// `Gen(level, _)`, return `(succ_count, level)`. Returns `None` for
/// anything that isn't of shape `ŝⁿ (neutral size var)` — non-rigid
/// values (e.g. projections, applications) fall through to the caller.
fn strip_to_rigid(v: &crate::nbe::val::Val) -> Option<(u32, u32)> {
    use crate::nbe::val::{Neut, Val};
    let mut n = 0u32;
    let mut cur = v;
    loop {
        match cur {
            Val::SizeSucc(inner) => {
                n = n.checked_add(1)?;
                cur = inner;
            }
            Val::Nt(Neut::Gen(level, _)) => {
                return Some((n, *level as u32));
            }
            _ => return None,
        }
    }
}

/// Strict-decrease on size values: `size_lt(s1, s2)` holds iff
/// `s1 < s2`, equivalently `ŝ(s1) ≤ s2`.
///
/// Used by termination checking (D19 §8.4): a recursive call on an
/// inductive value indexed by size `j` is permitted when `j < i` for
/// the outer recursion's size `i`. A productive corecursive call is
/// permitted when the observed output size is strictly greater than
/// the input — also a `size_lt` query.
pub fn size_lt(s1: &crate::nbe::val::Val, s2: &crate::nbe::val::Val) -> bool {
    size_lt_with_hyps(s1, s2, &crate::nbe::sized_rigid::Tso::new())
}

/// Strict-decrease with rigid hypothesis consultation. See
/// [`size_le_with_hyps`] and [`size_lt`].
pub fn size_lt_with_hyps(
    s1: &crate::nbe::val::Val,
    s2: &crate::nbe::val::Val,
    tso: &crate::nbe::sized_rigid::Tso,
) -> bool {
    use crate::nbe::val::Val;
    size_le_with_hyps(&Val::SizeSucc(Box::new(s1.clone())), s2, tso)
}

#[cfg(test)]
mod tests {
    use super::*;

    // --- size_le partial order tests (Phase 11b step 15d) ---
    //
    // Cross-checks against the size ordering described in D19 §8.3
    // and the per-rule semantics in the doc comment on `size_le`.

    use crate::nbe::val::{Neut, Val};

    fn succ_val(v: Val) -> Val {
        Val::SizeSucc(Box::new(v))
    }

    fn size_neut(id: usize) -> Val {
        Val::Nt(Neut::Gen(id, format!("s{id}")))
    }

    #[test]
    fn size_inf_is_top() {
        // Anything ≤ ∞.
        assert!(size_le(&Val::SizeInf, &Val::SizeInf));
        assert!(size_le(&succ_val(Val::SizeInf), &Val::SizeInf));
        assert!(size_le(&size_neut(0), &Val::SizeInf));
        assert!(size_le(&succ_val(size_neut(0)), &Val::SizeInf));
    }

    #[test]
    fn size_inf_not_below_finite() {
        // ∞ ≤ ŝ(s) must be false (infinity is the top, not succ of
        // anything except itself — and ∞-absorption collapses ŝ(∞)
        // at eval time, so ŝ(...) is never ∞ here).
        assert!(!size_le(&Val::SizeInf, &succ_val(size_neut(0))));
        assert!(!size_le(&Val::SizeInf, &size_neut(0)));
    }

    #[test]
    fn size_succ_is_reflexive_structurally() {
        // ŝ(s) ≤ ŝ(s) by the structural rule on top of reflexivity.
        let s = size_neut(0);
        assert!(size_le(&succ_val(s.clone()), &succ_val(s)));
    }

    #[test]
    fn size_succ_step_rule() {
        // s ≤ ŝ(s) admitted by the right-step rule.
        let s = size_neut(0);
        assert!(size_le(&s, &succ_val(s.clone())));
        // s ≤ ŝ(ŝ(s)) admitted (two applications of right-step).
        assert!(size_le(&s, &succ_val(succ_val(s.clone()))));
    }

    #[test]
    fn size_succ_step_rule_not_reversible() {
        // ŝ(s) ≤ s must not hold — the step only goes one direction.
        let s = size_neut(0);
        assert!(!size_le(&succ_val(s.clone()), &s));
    }

    #[test]
    fn distinct_neutrals_are_incomparable() {
        // No entailment between unrelated size variables here —
        // that's the job of the rigid-hypothesis solver.
        assert!(!size_le(&size_neut(0), &size_neut(1)));
        assert!(!size_le(&size_neut(1), &size_neut(0)));
    }

    #[test]
    fn neutral_reflexive() {
        // Same neutral compares equal.
        let s = size_neut(0);
        assert!(size_le(&s, &s));
    }

    #[test]
    fn succ_vs_succ_recurses() {
        // ŝ(a) ≤ ŝ(b) iff a ≤ b.
        let a = size_neut(0);
        let b = size_neut(1);
        // distinct neutrals: neither holds at the inner level so
        // neither holds outer.
        assert!(!size_le(&succ_val(a.clone()), &succ_val(b.clone())));
        // a ≤ ∞ at inner level ⇒ ŝ(a) ≤ ŝ(∞) — but ∞-absorption means
        // ŝ(∞) is never constructed; skip this case.
        // a ≤ ŝ(a) at inner level ⇒ ŝ(a) ≤ ŝ(ŝ(a)).
        assert!(size_le(&succ_val(a.clone()), &succ_val(succ_val(a))));
    }

    // --- size_le_with_hyps / size_lt_with_hyps (TSO-backed) tests ---
    //
    // Checked against MiniAgda's TSO semantics: edge
    // `child → (distance, parent)` encodes `child + distance ≤ parent`,
    // so `{i < j}` becomes `tso.insert(i_level, 1, j_level)`.

    use crate::nbe::sized_rigid::Tso;

    #[test]
    fn hyps_none_matches_size_le() {
        // Empty TSO: size_le_with_hyps ≡ size_le on all inputs.
        let s = size_neut(0);
        let empty = Tso::new();
        assert_eq!(size_le(&s, &s), size_le_with_hyps(&s, &s, &empty));
        assert_eq!(
            size_le(&s, &Val::SizeInf),
            size_le_with_hyps(&s, &Val::SizeInf, &empty)
        );
    }

    #[test]
    fn hyp_i_lt_j_admits_i_le_j() {
        // Given hypothesis i < j, prove i ≤ j.
        let mut tso = Tso::new();
        tso.insert(0, 1, 1); // level 0 < level 1
        assert!(size_le_with_hyps(&size_neut(0), &size_neut(1), &tso));
    }

    #[test]
    fn hyp_i_le_j_admits_i_le_j_but_not_strict() {
        // Given hypothesis i ≤ j (distance 0), prove i ≤ j but reject i < j.
        let mut tso = Tso::new();
        tso.insert(0, 0, 1); // level 0 ≤ level 1 (not strict)
        assert!(size_le_with_hyps(&size_neut(0), &size_neut(1), &tso));
        assert!(!size_lt_with_hyps(&size_neut(0), &size_neut(1), &tso));
    }

    #[test]
    fn hyp_i_lt_j_admits_i_lt_j() {
        // Given i < j, prove i < j (strict).
        let mut tso = Tso::new();
        tso.insert(0, 1, 1);
        assert!(size_lt_with_hyps(&size_neut(0), &size_neut(1), &tso));
    }

    #[test]
    fn hyp_i_lt_j_does_not_admit_j_le_i() {
        // Hypothesis is directional — i < j tells us nothing about j vs i.
        let mut tso = Tso::new();
        tso.insert(0, 1, 1);
        assert!(!size_le_with_hyps(&size_neut(1), &size_neut(0), &tso));
    }

    #[test]
    fn hyp_transitive_through_tso_chain() {
        // i < j, j < k ⊢ i < k (two hops in the TSO).
        let mut tso = Tso::new();
        tso.insert(0, 1, 1); // 0 < 1
        tso.insert(1, 1, 2); // 1 < 2
        assert!(size_lt_with_hyps(&size_neut(0), &size_neut(2), &tso));
        assert!(size_le_with_hyps(&size_neut(0), &size_neut(2), &tso));
    }

    #[test]
    fn hyp_i_lt_j_admits_succ_i_le_j() {
        // i < j ⊢ ŝ i ≤ j: offset n=1 on LHS matched by k=1 from TSO.
        let mut tso = Tso::new();
        tso.insert(0, 1, 1);
        assert!(size_le_with_hyps(
            &succ_val(size_neut(0)),
            &size_neut(1),
            &tso
        ));
    }

    #[test]
    fn hyp_i_lt_j_does_not_admit_succ_succ_i_le_j() {
        // i < j does NOT give ŝŝ i ≤ j (that needs i < j by 2).
        let mut tso = Tso::new();
        tso.insert(0, 1, 1);
        assert!(!size_le_with_hyps(
            &succ_val(succ_val(size_neut(0))),
            &size_neut(1),
            &tso
        ));
    }

    #[test]
    fn hyp_distance_2_admits_two_step_decrease() {
        // {i + 2 ≤ j} ⊢ ŝŝ i ≤ j.
        let mut tso = Tso::new();
        tso.insert(0, 2, 1);
        assert!(size_le_with_hyps(
            &succ_val(succ_val(size_neut(0))),
            &size_neut(1),
            &tso
        ));
    }

    // --- size_lt (strict decrease) tests ---

    #[test]
    fn size_lt_anything_below_inf() {
        // Any size is strictly below ∞.
        assert!(size_lt(&Val::SizeInf, &Val::SizeInf)); // ŝ(∞) absorbs to ∞ and ∞ ≤ ∞
        assert!(size_lt(&size_neut(0), &Val::SizeInf));
        assert!(size_lt(&succ_val(size_neut(0)), &Val::SizeInf));
    }

    #[test]
    fn size_lt_step_succ() {
        // s < ŝ(s) (the canonical strict-decrease witness).
        let s = size_neut(0);
        assert!(size_lt(&s, &succ_val(s.clone())));
    }

    #[test]
    fn size_lt_not_reflexive_on_neutral() {
        // s < s must be false for a bare neutral — no strict order.
        let s = size_neut(0);
        assert!(!size_lt(&s, &s));
    }

    #[test]
    fn size_lt_distinct_neutrals_incomparable() {
        // Unrelated neutrals: neither strict order holds.
        assert!(!size_lt(&size_neut(0), &size_neut(1)));
        assert!(!size_lt(&size_neut(1), &size_neut(0)));
    }

    #[test]
    fn size_lt_succ_step_transitive() {
        // s < ŝ(ŝ(s)) — two succ layers between.
        let s = size_neut(0);
        assert!(size_lt(&s, &succ_val(succ_val(s.clone()))));
    }
}
