// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type ResourceData = eigenius::component::types::ResourceData;
pub type Iri = eigenius::component::types::Iri;
pub type ComponentResult = eigenius::component::types::ComponentResult;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_execute_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let len1 = arg3;
    let result2 = T::execute(
        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
    );
    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result2 {
        Ok(e) => {
            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
            let eigenius::component::types::ComponentResult { output: output4 } = e;
            let vec5 = (output4).into_boxed_slice();
            let ptr5 = vec5.as_ptr().cast::<u8>();
            let len5 = vec5.len();
            ::core::mem::forget(vec5);
            *ptr3.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
            *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5
                .cast_mut();
        }
        Err(e) => {
            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
            let vec6 = (e.into_bytes()).into_boxed_slice();
            let ptr6 = vec6.as_ptr().cast::<u8>();
            let len6 = vec6.len();
            ::core::mem::forget(vec6);
            *ptr3.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
            *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6
                .cast_mut();
        }
    };
    ptr3
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_execute<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base3 = l1;
            let len3 = l2;
            _rt::cabi_dealloc(base3, len3 * 1, 1);
        }
        _ => {
            let l4 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l5 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l4, l5, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_component_iri_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::component_iri();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec2 = (result0.into_bytes()).into_boxed_slice();
    let ptr2 = vec2.as_ptr().cast::<u8>();
    let len2 = vec2.len();
    ::core::mem::forget(vec2);
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_component_iri<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
pub trait Guest {
    fn execute(
        input: ResourceData,
        argument: ResourceData,
    ) -> Result<ComponentResult, _rt::String>;
    fn component_iri() -> Iri;
}
#[doc(hidden)]
macro_rules! __export_world_eigenius_component_io_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "execute")] unsafe extern "C" fn
        export_execute(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8, arg3 : usize,) ->
        * mut u8 { unsafe { $($path_to_types)*:: _export_execute_cabi::<$ty > (arg0,
        arg1, arg2, arg3) } } #[unsafe (export_name = "cabi_post_execute")] unsafe extern
        "C" fn _post_return_execute(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_execute::<$ty > (arg0) } } #[unsafe (export_name =
        "component-iri")] unsafe extern "C" fn export_component_iri() -> * mut u8 {
        unsafe { $($path_to_types)*:: _export_component_iri_cabi::<$ty > () } } #[unsafe
        (export_name = "cabi_post_component-iri")] unsafe extern "C" fn
        _post_return_component_iri(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_component_iri::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_eigenius_component_io_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 3 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 3 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod eigenius {
    pub mod component {
        /// Types shared across all extension interfaces.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// A CBOR-encoded Eigon resource.
            pub type ResourceData = _rt::Vec<u8>;
            /// An IRI string.
            pub type Iri = _rt::String;
            /// Result of a component execution.
            #[derive(Clone)]
            pub struct ComponentResult {
                /// CBOR-encoded output resource.
                pub output: ResourceData,
            }
            impl ::core::fmt::Debug for ComponentResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ComponentResult")
                        .field("output", &self.output)
                        .finish()
                }
            }
        }
        /// Read-only access to the knowledge graph.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod read_access {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type ResourceData = super::super::super::eigenius::component::types::ResourceData;
            pub type Iri = super::super::super::eigenius::component::types::Iri;
            #[allow(unused_unsafe, clippy::all)]
            /// Resolve a resource by IRI from the layer chain.
            pub fn resolve(iri: &str) -> Option<ResourceData> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = iri;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "eigenius:component/read-access@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "resolve"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result7 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                _rt::Vec::from_raw_parts(l4.cast(), len6, len6)
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result7
                }
            }
        }
        /// Query access to the knowledge graph.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod query_access {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type ResourceData = super::super::super::eigenius::component::types::ResourceData;
            #[allow(unused_unsafe, clippy::all)]
            /// Execute an EigenQL query.
            pub fn query(eigenql: &str) -> Result<_rt::Vec<ResourceData>, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = eigenql;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "eigenius:component/query-access@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "query"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result13 = match l3 {
                        0 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base9 = l4;
                                let len9 = l5;
                                let mut result9 = _rt::Vec::with_capacity(len9);
                                for i in 0..len9 {
                                    let base = base9
                                        .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                    let e9 = {
                                        let l6 = *base.add(0).cast::<*mut u8>();
                                        let l7 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len8 = l7;
                                        _rt::Vec::from_raw_parts(l6.cast(), len8, len8)
                                    };
                                    result9.push(e9);
                                }
                                _rt::cabi_dealloc(
                                    base9,
                                    len9 * (2 * ::core::mem::size_of::<*const u8>()),
                                    ::core::mem::size_of::<*const u8>(),
                                );
                                result9
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l10 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l11 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len12 = l11;
                                let bytes12 = _rt::Vec::from_raw_parts(
                                    l10.cast(),
                                    len12,
                                    len12,
                                );
                                _rt::string_lift(bytes12)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result13
                }
            }
        }
        /// IO access: dispatch calls to other components (including LLM adapters).
        /// Only provided to orchestrator-hosted WASM components (capability_level=io).
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod io_access {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type ResourceData = super::super::super::eigenius::component::types::ResourceData;
            pub type Iri = super::super::super::eigenius::component::types::Iri;
            #[allow(unused_unsafe, clippy::all)]
            /// Dispatch to another registered component by IRI.
            /// The input and argument are CBOR-encoded Eigon resources.
            /// Returns the component's output as CBOR.
            pub fn dispatch_component(
                component_iri: &str,
                input: &[u8],
                argument: &[u8],
            ) -> Result<ResourceData, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = component_iri;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = input;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = argument;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "eigenius:component/io-access@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "dispatch-component"]
                        fn wit_import4(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import4(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import4(
                            ptr0.cast_mut(),
                            len0,
                            ptr1.cast_mut(),
                            len1,
                            ptr2.cast_mut(),
                            len2,
                            ptr3,
                        )
                    };
                    let l5 = i32::from(*ptr3.add(0).cast::<u8>());
                    let result12 = match l5 {
                        0 => {
                            let e = {
                                let l6 = *ptr3
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l7 = *ptr3
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len8 = l7;
                                _rt::Vec::from_raw_parts(l6.cast(), len8, len8)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l9 = *ptr3
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l10 = *ptr3
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len11 = l10;
                                let bytes11 = _rt::Vec::from_raw_parts(
                                    l9.cast(),
                                    len11,
                                    len11,
                                );
                                _rt::string_lift(bytes11)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result12
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_eigenius_component_io_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_eigenius_component_io_cabi!($ty
        with_types_in $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_eigenius_component_io_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:eigenius:component@0.1.0:eigenius-component-io:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 816] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa4\x05\x01A\x02\x01\
A\x13\x01B\x06\x01p}\x04\0\x0dresource-data\x03\0\0\x01s\x04\0\x03iri\x03\0\x02\x01\
r\x01\x06output\x01\x04\0\x10component-result\x03\0\x04\x03\0\x1eeigenius:compon\
ent/types@0.1.0\x05\0\x02\x03\0\0\x0dresource-data\x03\0\x0dresource-data\x03\0\x01\
\x02\x03\0\0\x03iri\x03\0\x03iri\x03\0\x03\x02\x03\0\0\x10component-result\x03\0\
\x10component-result\x03\0\x05\x01B\x07\x02\x03\x02\x01\x01\x04\0\x0dresource-da\
ta\x03\0\0\x02\x03\x02\x01\x03\x04\0\x03iri\x03\0\x02\x01k\x01\x01@\x01\x03iri\x03\
\0\x04\x04\0\x07resolve\x01\x05\x03\0$eigenius:component/read-access@0.1.0\x05\x07\
\x01B\x06\x02\x03\x02\x01\x01\x04\0\x0dresource-data\x03\0\0\x01p\x01\x01j\x01\x02\
\x01s\x01@\x01\x07eigenqls\0\x03\x04\0\x05query\x01\x04\x03\0%eigenius:component\
/query-access@0.1.0\x05\x08\x01B\x07\x02\x03\x02\x01\x01\x04\0\x0dresource-data\x03\
\0\0\x02\x03\x02\x01\x03\x04\0\x03iri\x03\0\x02\x01j\x01\x01\x01s\x01@\x03\x0dco\
mponent-iri\x03\x05input\x01\x08argument\x01\0\x04\x04\0\x12dispatch-component\x01\
\x05\x03\0\"eigenius:component/io-access@0.1.0\x05\x09\x01j\x01\x06\x01s\x01@\x02\
\x05input\x02\x08argument\x02\0\x0a\x04\0\x07execute\x01\x0b\x01@\0\0\x04\x04\0\x0d\
component-iri\x01\x0c\x04\0.eigenius:component/eigenius-component-io@0.1.0\x04\0\
\x0b\x1b\x01\0\x15eigenius-component-io\x03\0\0\0G\x09producers\x01\x0cprocessed\
-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
